# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  peer0.org2.prototipo.com:
  peer1.org2.prototipo.com:
  
networks:
  bymn:
    external:
      name: fabric
    


services:
  ca2:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.prototipo.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.prototipo.com-cert.pem
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.prototipo.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8b29feae5f7360e4059dcd624f30e628f8705327a87266f4bbc771126a729e31_sk
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8b29feae5f7360e4059dcd624f30e628f8705327a87266f4bbc771126a729e31_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.prototipo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8b29feae5f7360e4059dcd624f30e628f8705327a87266f4bbc771126a729e31_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.prototipo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca2
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
              constraints:
                - node.hostname == blocksaas-01

    ports:
     - published: 8054
       target: 8054
       mode: host
    networks:
      bymn:
        aliases:
          - ca.org2.prototipo.com

  org2peer0:
    container_name: org2peer0
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org2.prototipo.com
      - CORE_PEER_ADDRESS=peer0.org2.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.prototipo.com/peers/peer0.org2.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.prototipo.com/peers/peer0.org2.prototipo.com/tls:/etc/hyperledger/fabric/tls
        #- ./crypto-config/peerOrganizations/org2.prototipo.com/peers/peer0.org2.prototipo.com/ca:/etc/hyperledger/fabric/ca
        - peer0.org2.prototipo.com:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
              constraints:
                - node.hostname == blocksaas-01

    ports:
            - published: 7061
              target: 7051
              mode: host
            - published: 7063
              target: 7053
              mode: host
    networks:
      bymn:
        aliases:
          - peer0.org2.prototipo.com

  org2peer1:
    container_name: org2peer1
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.org2.prototipo.com
      - CORE_PEER_ADDRESS=peer1.org2.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.prototipo.com/peers/peer1.org2.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.prototipo.com/peers/peer1.org2.prototipo.com/tls:/etc/hyperledger/fabric/tls
        #- ./crypto-config/peerOrganizations/org2.prototipo.com/peers/peer1.org2.prototipo.com/ca:/etc/hyperledger/fabric/ca
        - peer1.org2.prototipo.com:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
              constraints:
                - node.hostname == blocksaas-01

    ports:
            - published: 8061
              target: 7051
              mode: host
            - published: 8063
              target: 7053
              mode: host
    networks:
      bymn:
        aliases:
          - peer1.org2.prototipo.com

