# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  peer0.org1.prototipo.com:
  peer1.org1.prototipo.com:
  peer2.org1.prototipo.com:
  peer3.org1.prototipo.com:
  
networks:
  bymn:
    external:
      name: fabric
    
services:
  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.prototipo.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.prototipo.com-cert.pem
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.prototipo.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d5a75425ea58864c1461a73af08af0d94a82c249a9a221d7510095f3c7ea7506_sk
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d5a75425ea58864c1461a73af08af0d94a82c249a9a221d7510095f3c7ea7506_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.prototipo.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d5a75425ea58864c1461a73af08af0d94a82c249a9a221d7510095f3c7ea7506_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.prototipo.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca1
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure

    ports:
     - published: 7054
       target: 7054
       mode: host
    networks:
      bymn:
        aliases:
          - ca.org1.prototipo.com

  org1peer0:
    container_name: org1peer0
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.prototipo.com
      - CORE_PEER_ADDRESS=peer0.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=blocksaas
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=blocksaas1988
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=10.1.2.14:5984

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com/tls:/etc/hyperledger/fabric/tls
        #- ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com/ca:/etc/hyperledger/fabric/ca
        - peer0.org1.prototipo.com:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure

    ports:
            - published: 7051
              target: 7051
              mode: host
            - published: 7053
              target: 7053
              mode: host
    networks:
      bymn:
        aliases:
          - peer0.org1.prototipo.com
           

  org1peer1:
    container_name: org1peer1
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.org1.prototipo.com
      - CORE_PEER_ADDRESS=peer1.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=blocksaas
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=blocksaas1988
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=10.1.2.15:6984

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer1.org1.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer1.org1.prototipo.com/tls:/etc/hyperledger/fabric/tls
        #- ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer1.org1.prototipo.com/ca:/etc/hyperledger/fabric/ca
        - peer1.org1.prototipo.com:/var/hyperledger/production
    
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure

    ports:
            - published: 8051
              target: 7051
              mode: host
            - published: 8053
              target: 7053
              mode: host
    networks:
      bymn:
        aliases:
          - peer1.org1.prototipo.com

  org1peer2:
    container_name: org1peer2
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer2.org1.prototipo.com
      - CORE_PEER_ADDRESS=peer2.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=blocksaas
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=blocksaas1988
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=10.1.2.16:7984

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer2.org1.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer2.org1.prototipo.com/tls:/etc/hyperledger/fabric/tls
        #- ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer2.org1.prototipo.com/ca:/etc/hyperledger/fabric/ca
        - peer2.org1.prototipo.com:/var/hyperledger/production

    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure

    ports:
            - published: 9051
              target: 7051
              mode: host
            - published: 9053
              target: 7053
              mode: host
    networks:
      bymn:
        aliases:
          - peer2.org1.prototipo.com

  org1peer3:
    container_name: org1peer3
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer3.org1.prototipo.com
      - CORE_PEER_ADDRESS=peer3.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=blocksaas
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=blocksaas1988
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=10.1.2.17:8984

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer3.org1.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer3.org1.prototipo.com/tls:/etc/hyperledger/fabric/tls
        #- ./crypto-config/peerOrganizations/org1.prototipo.com/peers/peer3.org1.prototipo.com/ca:/etc/hyperledger/fabric/ca
        - peer3.org1.prototipo.com:/var/hyperledger/production

    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure

    ports:
            - published: 10051
              target: 7051
              mode: host
            - published: 10053
              target: 7053
              mode: host
    networks:
      bymn:
        aliases:
          - peer3.org1.prototipo.com
 
  org1cli:
    container_name: org1cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure

    environment:

      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.prototipo.com/users/Admin@org1.prototipo.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - bymn

